######################################################################
#
# File name : clk_timer_tb.udo
# Created on: Tue Dec 17 12:46:47 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
