######################################################################
#
# File name : seven_srg_mux_tb_wave.do
# Created on: Thu Dec 19 15:41:39 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
