######################################################################
#
# File name : seven_srg_mux_tb_compile.do
# Created on: Thu Dec 19 15:41:32 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\modeltech_pe_10.4c\\win32pe\\vlib work
C:\\modeltech_pe_10.4c\\win32pe\\vlib msim

C:\\modeltech_pe_10.4c\\win32pe\\vlib msim/xil_defaultlib

C:\\modeltech_pe_10.4c\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

C:\\modeltech_pe_10.4c\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"../../../number_guess.srcs/sources_1/new/ps2_keyboard.v" \
"../../../number_guess.srcs/sources_1/new/MP3.v" \
"../../../number_guess.srcs/sources_1/new/top.v" \
"../../../number_guess.srcs/sources_1/new/random_number_generator.v" \
"../../../number_guess.srcs/sources_1/new/clk_divider.v" \
"../../../number_guess.srcs/sources_1/new/mux_7seg.v" \
"../../../number_guess.srcs/sim_1/imports/new/clk_timer_tb.v" \
"../../../number_guess.srcs/sim_1/imports/new/seven_seg_mux_tb.v" \
"../../../number_guess.srcs/sim_1/imports/new/ps2_keyboard_tb.v" \


# compile glbl module
C:\\modeltech_pe_10.4c\\win32pe\\vlog -work xil_defaultlib "glbl.v"

quit -force

