######################################################################
#
# File name : seven_srg_mux_tb_simulate.do
# Created on: Thu Dec 19 15:41:39 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.seven_srg_mux_tb xil_defaultlib.glbl

do {seven_srg_mux_tb_wave.do}

view wave
view structure
view signals

do {seven_srg_mux_tb.udo}

run 1000ns
