# 
# Synthesis run script generated by Vivado
# 

set_param simulator.modelsimInstallPath C:/modeltech_pe_10.4c/win32pe
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/vivado/number_guess/number_guess.cache/wt [current_project]
set_property parent.project_path D:/vivado/number_guess/number_guess.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  D:/vivado/number_guess/number_guess.srcs/sources_1/new/ps2_keyboard.v
  D:/vivado/number_guess/number_guess.srcs/sources_1/new/MP3.v
  D:/vivado/number_guess/number_guess.srcs/sources_1/new/top.v
  D:/vivado/number_guess/number_guess.srcs/sources_1/new/random_number_generator.v
  D:/vivado/number_guess/number_guess.srcs/sources_1/new/clk_divider.v
  D:/vivado/number_guess/number_guess.srcs/sources_1/new/mux_7seg.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/vivado/number_guess/number_guess.srcs/constrs_1/new/clk.xdc
set_property used_in_implementation false [get_files D:/vivado/number_guess/number_guess.srcs/constrs_1/new/clk.xdc]

read_xdc D:/vivado/number_guess/number_guess.srcs/constrs_1/new/display7.xdc
set_property used_in_implementation false [get_files D:/vivado/number_guess/number_guess.srcs/constrs_1/new/display7.xdc]


synth_design -top top -part xc7a100tcsg324-1


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
